### ISSUE TITLE
Errors in python building app..

### ISSUE THREAD

**Issue by missionmankind** [KR0SIV/op25mobileControlHead#1]
im getting these errors after copy and pasting into python app on my android.
What is wrong here with the OP25 python code.
im using Pydroid 3 app for Android on my Samsung S9+ running Android 10

this comes up as red text as if its a error when trying to run the code...

"Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/temp_iiec_codefile.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'"

**Comment by KR0SIV** [comment]
The traceback error tells you the issue: 

ModuleNotFoundError: No module named 'requests'"


You need to install the requests module, and a few others.
The pydroid3 app has a "pip" or "library" section where you can add or install such modules.

**Comment by tctx79** [comment]
I'm having the same issue, but a different module.  I did pip install serial (running on Windows 10) and it installed.

However, when I run mobilehead.py I get this:

 import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial.tools'

A pip install for serial.tools throws an error.  Any thoughts?
